import { payslipFormSchema, type PayslipFormValues } from './payslip.schema';
// payslipFormSchema's ZodType input differs from output due to .default() — FormConfig handles this
import { PayslipFormSections } from './components/PayslipFormSections';
import { PayslipPDF } from './components/PayslipPDF';
import type { FormConfig } from '../forms/types/form-config.types';
import type { IEmployee, ICompany, IForm } from '@payslips-maker/shared';

export const payslipFormConfig: FormConfig<PayslipFormValues> = {
  labelHe: 'תלוש שכר',
  formType: 'payslip',
  schema: payslipFormSchema,

  defaultValues: (employee: IEmployee, company: ICompany | null) => {
    const now = new Date();
    return ({
    period: { month: now.getMonth() + 1, year: now.getFullYear() },
    employeeInfo: {
      fullName: employee.fullName,
      idNumber: employee.passportNumber,
      nationality: employee.nationality,
      employerName: company?.name ?? {},
      employerTaxId: company?.ein ?? '',
      employerAddress: undefined,
      employerCity: undefined,
      employerZip: undefined,
      employerRegistrationNumber: undefined,
      taxFileNumber: undefined,
      employeeNumber: undefined,
      jobTitle: undefined,
      department: undefined,
      familyStatus: undefined,
      grade: undefined,
      jobFraction: 1,
      employmentStartDate: undefined,
      taxCalcType: undefined,
      nationalInsuranceType: undefined,
      salaryBasis: 'monthly' as const,
      employeeAddress: undefined,
      employeeCity: undefined,
      employeeZip: undefined,
    },
    workDetails: {
      standardDays: 22,
      workedDays: 22,
      vacationDays: 0,
      sickDays: 0,
      holidayDays: 0,
      overtime100h: 0,
      overtime125h: 0,
      overtime150h: 0,
    },
    payCalculation: {
      dailyRate: 0,
      baseSalary: 0,
      overtimePay: 0,
      vacationPay: 0,
      grossSalary: 0,
    },
    deductions: {
      incomeTax: 0,
      nationalInsurance: 0,
      healthInsurance: 0,
      otherDeductions: 0,
    },
    employerContributions: {
      nationalInsurance: 0,
      pension: 0,
      pensionFund: undefined,
      pensionEmployeeRate: 0,
      pensionEmployerRate: 0,
      severanceFund: 0,
      educationFund: 0,
      educationFundEmployee: 0,
    },
    netSalary: 0,
    paymentInfo: {
      paymentMethod: 'bank',
      bankName: '',
      accountNumber: '',
      branchNumber: '',
    },
    customPayItems: [],
    vacationAccount: null,
    sickAccount: null,
  });
  },

  fromApiForm: (form: IForm): PayslipFormValues => ({
    period: form.period,
    employeeInfo: {
      fullName: form.employeeInfo.fullName,
      idNumber: form.employeeInfo.idNumber,
      nationality: form.employeeInfo.nationality,
      employerName: form.employeeInfo.employerName,
      employerTaxId: form.employeeInfo.employerTaxId,
      employerAddress: form.employeeInfo.employerAddress,
      employerCity: form.employeeInfo.employerCity,
      employerZip: form.employeeInfo.employerZip,
      employerRegistrationNumber: form.employeeInfo.employerRegistrationNumber,
      taxFileNumber: form.employeeInfo.taxFileNumber,
      employeeNumber: form.employeeInfo.employeeNumber,
      jobTitle: form.employeeInfo.jobTitle,
      department: form.employeeInfo.department,
      familyStatus: form.employeeInfo.familyStatus,
      grade: form.employeeInfo.grade,
      jobFraction: form.employeeInfo.jobFraction ?? 1,
      employmentStartDate: form.employeeInfo.employmentStartDate,
      taxCalcType: form.employeeInfo.taxCalcType,
      nationalInsuranceType: form.employeeInfo.nationalInsuranceType,
      salaryBasis: form.employeeInfo.salaryBasis ?? 'monthly',
      employeeAddress: form.employeeInfo.employeeAddress,
      employeeCity: form.employeeInfo.employeeCity,
      employeeZip: form.employeeInfo.employeeZip,
    },
    workDetails: form.workDetails,
    payCalculation: form.payCalculation,
    deductions: form.deductions,
    employerContributions: {
      nationalInsurance: form.employerContributions.nationalInsurance,
      pension: form.employerContributions.pension,
      pensionFund: form.employerContributions.pensionFund,
      pensionEmployeeRate: form.employerContributions.pensionEmployeeRate ?? 0,
      pensionEmployerRate: form.employerContributions.pensionEmployerRate ?? 0,
      severanceFund: form.employerContributions.severanceFund ?? 0,
      educationFund: form.employerContributions.educationFund ?? 0,
      educationFundEmployee: form.employerContributions.educationFundEmployee ?? 0,
    },
    netSalary: form.netSalary,
    paymentInfo: form.paymentInfo,
    customPayItems: form.customPayItems ?? [],
    vacationAccount: form.vacationAccount ?? null,
    sickAccount: form.sickAccount ?? null,
  }),

  FormSections: PayslipFormSections,
  PDFDocument: PayslipPDF,
};
