name: Deploy All

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-server:
    uses: ./.github/workflows/deploy-server.yml
    secrets: inherit

  deploy-client:
    uses: ./.github/workflows/deploy-client.yml
    secrets: inherit
